version: 2
distribution_spec:
  description: TrustyAI distribution of Llama Stack
  providers:
    inference:
    - provider_type: remote::vllm
    - provider_type: inline::sentence-transformers
    vector_io:
    - provider_type: inline::milvus
    safety:
    - provider_type: remote::trustyai_fms
      module: llama_stack_provider_trustyai_fms==0.2.2
    agents:
    - provider_type: inline::meta-reference
    eval:
    - provider_type: remote::trustyai_lmeval
      module: llama_stack_provider_lmeval==0.2.4
    - provider_type: inline::trustyai_garak
      module: llama_stack_provider_trustyai_garak==0.1.4
    - provider_type: remote::trustyai_garak
      module: llama_stack_provider_trustyai_garak[remote]==0.1.4
    datasetio:
    - provider_type: remote::huggingface
    - provider_type: inline::localfs
    scoring:
    - provider_type: inline::basic
    - provider_type: inline::llm-as-judge
    - provider_type: inline::braintrust
    telemetry:
    - provider_type: inline::meta-reference
    tool_runtime:
    - provider_type: remote::brave-search
    - provider_type: remote::tavily-search
    - provider_type: inline::rag-runtime
    - provider_type: remote::model-context-protocol
  container_image: registry.access.redhat.com/ubi9/python-312:latest
additional_pip_packages:
- aiosqlite
- sqlalchemy[asyncio]
image_type: container
image_name: llama-stack-trustyai
external_providers_dir: trustyai-distribution/providers.d
