FROM registry.access.redhat.com/ubi9/python-312:latest
WORKDIR /opt/app-root

# Switch to root for package installation
USER root
RUN pip install sqlalchemy # somehow sqlalchemy[asyncio] is not sufficient
{dependencies}
RUN pip install --no-cache llama-stack==0.2.22

# Switch back to non-root user
USER 1001
RUN mkdir -p ${{HOME}}/.llama ${{HOME}}/.cache
COPY trustyai-distribution/run.yaml ${{APP_ROOT}}/run.yaml

ENTRYPOINT ["python", "-m", "llama_stack.core.server.server", "/opt/app-root/run.yaml"]
